import os
import re
import time
import random
import sqlite3
import requests
from bs4 import BeautifulSoup
from concurrent.futures import ThreadPoolExecutor, as_completed

DB_PATH = "hk_racing.db"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7",
            "Referer": "https://racing.hkjc.com/"
            }

            def init_tables(conn):
                c = conn.cursor()
                    c.execute("""
                        CREATE TABLE IF NOT EXISTS horse_weights_allowance (
                                id INTEGER PRIMARY KEY AUTOINCREMENT,
                                        race_id TEXT,
                                                race_date TEXT,
                                                        race_no INTEGER,
                                                                horse_code TEXT,
                                                                        horse_name TEXT,
                                                                                jockey TEXT,
                                                                                        actual_weight REAL,
                                                                                                declared_weight REAL,
                                                                                                        weight_change REAL,
                                                                                                                jockey_allowance INTEGER DEFAULT 0
                                                                                                                    )""")
                                                                                                                        c.execute("""
                                                                                                                            CREATE TABLE IF NOT EXISTS track_environment_detail (
                                                                                                                                    race_id TEXT PRIMARY KEY,
                                                                                                                                            race_date TEXT,
                                                                                                                                                    track_info TEXT,
                                                                                                                                                            going TEXT,
                                                                                                                                                                    penetrometer_reading REAL
                                                                                                                                                                        )""")
                                                                                                                                                                            c.execute("CREATE INDEX IF NOT EXISTS idx_hwa_r ON horse_weights_allowance(race_id)")
                                                                                                                                                                                c.execute("CREATE INDEX IF NOT EXISTS idx_hwa_h ON horse_weights_allowance(horse_code)")
                                                                                                                                                                                    conn.commit()
                                                                                                                                                                                    
                                                                                                                                                                                    def fetch_track_env(r_date):
                                                                                                                                                                                        date_str = str(r_date).replace("-", "/")
                                                                                                                                                                                            date_id = str(r_date).replace("-", "")
                                                                                                                                                                                                race_id = f"{date_id}01"
                                                                                                                                                                                                    url = f"https://racing.hkjc.com/racing/information/Chinese/Racing/LocalResults.aspx?RaceDate={date_str}&RaceNo=1"
                                                                                                                                                                                                        
                                                                                                                                                                                                            session = requests.Session()
                                                                                                                                                                                                                session.headers.update(HEADERS)
                                                                                                                                                                                                                    
                                                                                                                                                                                                                        going = ""
                                                                                                                                                                                                                            track_info = ""
                                                                                                                                                                                                                                pene = None
                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                            resp = session.get(url, timeout=10)
                                                                                                                                                                                                                                                    if resp.status_code == 200 and "沒有相關賽事" not in resp.text:
                                                                                                                                                                                                                                                                soup = BeautifulSoup(resp.content, "html.parser")
                                                                                                                                                                                                                                                                            page_text = soup.get_text()
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                    m_going = re.search(r'場地狀況\s*[:：]\s*([^\s<]+)', page_text)
                                                                                                                                                                                                                                                                                                                going = m_going.group(1) if m_going else ""
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                        m_track = re.search(r'賽道\s*[:：]\s*([^<>\r\n]+)', page_text)
                                                                                                                                                                                                                                                                                                                                                    track_info = m_track.group(1).strip() if m_track else ""
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                            m_pene = re.search(r'壓地儀讀數\s*[:：]\s*(\d+\.?\d*)', page_text)
                                                                                                                                                                                                                                                                                                                                                                                        pene = float(m_pene.group(1)) if m_pene else None
                                                                                                                                                                                                                                                                                                                                                                                            except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                    pass
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                time.sleep(random.uniform(0.2, 0.4))
                                                                                                                                                                                                                                                                                                                                                                                                                    return race_id, str(r_date), track_info, going, pene
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                    def main():
                                                                                                                                                                                                                                                                                                                                                                                                                        if not os.path.exists(DB_PATH):
                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"找不到資料庫: {DB_PATH}")
                                                                                                                                                                                                                                                                                                                                                                                                                                        return
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                            conn = sqlite3.connect(DB_PATH)
                                                                                                                                                                                                                                                                                                                                                                                                                                                init_tables(conn)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    c = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        # 1. 注入全量負磅與讓磅利益 (約 2 秒)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("[1/2] 正在秒級注入 5 年全量負磅與見習騎師讓磅利益...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                c.execute("SELECT race_id, race_date, race_no, horse_code, horse_name, jockey, actual_weight FROM race_results ORDER BY horse_code ASC, race_date ASC, race_no ASC")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rows = c.fetchall()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        weights_data = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for r in rows:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    race_id, r_date, r_no, h_code, h_name, jockey_str, act_wt = r
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            allow_m = re.search(r'\(-?(\d+)\)', str(jockey_str or ''))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    allowance = int(allow_m.group(1)) if allow_m else 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            clean_jockey = re.sub(r'\(.*?\)', '', str(jockey_str or '')).strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    weights_data.append((race_id, r_date, r_no, h_code, h_name, clean_jockey, act_wt, 0.0, 0.0, allowance))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c.execute("DELETE FROM horse_weights_allowance")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c.executemany("INSERT INTO horse_weights_allowance VALUES (NULL,?,?,?,?,?,?,?,?,?,?)", weights_data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"  [✔] 成功寫入負磅與讓磅表: {len(weights_data)} 筆！")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # 2. 5 線程極速抓取 440 賽日跑道環境與硬度 (約 90 秒)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("[2/2] 正在 5 線程極速抓取 440 賽日移欄跑道與壓地儀讀數...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c.execute("SELECT DISTINCT race_date FROM race_results ORDER BY race_date ASC")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    distinct_dates = [row[0] for row in c.fetchall()]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        track_rows = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with ThreadPoolExecutor(max_workers=5) as executor:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    futures = {executor.submit(fetch_track_env, d): d for d in distinct_dates}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for future in as_completed(futures):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        track_rows.append(future.result())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c.executemany("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                INSERT OR REPLACE INTO track_environment_detail (race_id, race_date, track_info, going, penetrometer_reading)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    VALUES (?, ?, ?, ?, ?)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """, track_rows)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"  [✔] 成功寫入 440 賽日跑道環境: {len(track_rows)} 筆！")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 3. 15 大專項表終極大盤點
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\n==================================================")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("🏆 香港賽馬 15 大專項表【極致全量大滿貫】終極審查報告 🏆")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("==================================================")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tables = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "race_results", "sectionals", "dividends", "races_meta",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "trackwork", "barrier_trials", "veterinary_records", "stewards_incidents",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "horse_weights_allowance", "track_environment_detail",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "stable_transfers", "conghua_movements", "horse_lifecycle_extended",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "trump_cards_priority", "running_comments"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for t in tables:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c.execute(f"SELECT COUNT(*) FROM {t}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cnt = c.fetchone()[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"  ✔ {t.ljust(26)} : {cnt:,} 筆")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"  ✖ {t.ljust(26)} : 資料表未建立")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("==================================================\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("[🎉 大功告成！] 終極合體旗艦庫已圓滿誕生！")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main()
